version: "3.8"
services:
  eureka:
    image: steeltoeoss/eureka-server
    container_name: eureka
    ports:
      - "8761:8761"

  catalog:
    build: ./CatalogService
    container_name: CatalogService
    ports:
      - "9000:80"
    depends_on:
      - "catalogdb"
  catalogdb:
    build: ./CatalogService/catalogdb
    container_name: sql-catalog
    ports:
      - "1433:1433"

  user:
    build: ./UserService
    container_name: UserService
    ports:
      - "9001:80"
    depends_on:
      - "userdb"
  userdb:
    build: ./UserService/usersdb
    container_name: sql-users
    ports:
      - "1444:1433"

  card:
    build: ./CardService
    container_name: CardService
    ports:
      - "9002:80"
    depends_on:
      - "carddb"
  carddb:
    build: ./CardService/carddb
    container_name: sql-cards
    ports:
      - "1455:1433"
  
  basket:
    build: ./BasketService
    container_name: BasketService
    ports:
      - "9003:80"
    depends_on:
      - "basketdb"
  basketdb:
    build: ./BasketService/basketdb
    container_name: sql-basket
    ports:
      - "1466:1433"
  
  checkout:
    build: ./CheckoutService
    container_name: CheckoutService
    ports:
      - "9004:80"
    depends_on:
      - "checkoutdb"
  checkoutdb:
    build: ./CheckoutService/checkoutdb
    container_name: sql-checkout
    ports:
      - "1477:1433"

  apigateway:
    container_name: apigateway
    build:
      context: ./ApiGateway
      dockerfile: 2.dockerfile
    image: apigateway:1    
    ports:
      - "8888:8888"
    depends_on:
      - eureka


networks:
  default:
    name: netSEN300
    external: true